// 
// Decompiled by Procyon v0.5.36
// 

package org.mortbay.jetty;

import org.mortbay.io.ByteArrayBuffer;
import org.mortbay.io.Buffer;
import org.mortbay.io.BufferCache;

public class HttpStatus
{
    public static final String Continue = "Continue";
    public static final String Switching_Protocols = "Switching Protocols";
    public static final String Processing = "Processing";
    public static final String OK = "OK";
    public static final String Created = "Created";
    public static final String Accepted = "Accepted";
    public static final String Non_Authoritative_Information = "Non Authoritative Information";
    public static final String No_Content = "No Content";
    public static final String Reset_Content = "Reset Content";
    public static final String Partial_Content = "Partial Content";
    public static final String Multi_Status = "Multi Status";
    public static final String Multiple_Choices = "Multiple Choices";
    public static final String Moved_Permanently = "Moved Permanently";
    public static final String Moved_Temporarily = "Moved Temporarily";
    public static final String Found = "Found";
    public static final String See_Other = "See Other";
    public static final String Not_Modified = "Not Modified";
    public static final String Use_Proxy = "Use Proxy";
    public static final String Bad_Request = "Bad Request";
    public static final String Unauthorized = "Unauthorized";
    public static final String Payment_Required = "Payment Required";
    public static final String Forbidden = "Forbidden";
    public static final String Not_Found = "Not Found";
    public static final String Method_Not_Allowed = "Method Not Allowed";
    public static final String Not_Acceptable = "Not Acceptable";
    public static final String Proxy_Authentication_Required = "Proxy Authentication Required";
    public static final String Request_Timeout = "Request Timeout";
    public static final String Conflict = "Conflict";
    public static final String Gone = "Gone";
    public static final String Length_Required = "Length Required";
    public static final String Precondition_Failed = "Precondition Failed";
    public static final String Request_Entity_Too_Large = "Request Entity Too Large";
    public static final String Request_URI_Too_Large = "Request URI Too Large";
    public static final String Unsupported_Media_Type = "Unsupported Media Type";
    public static final String Requested_Range_Not_Satisfiable = "Requested Range Not Satisfiable";
    public static final String Expectation_Failed = "Expectation Failed";
    public static final String Unprocessable_Entity = "Unprocessable Entity";
    public static final String Locked = "Locked";
    public static final String Failed_Dependency = "Failed Dependency";
    public static final String Internal_Server_Error = "Internal Server Error";
    public static final String Not_Implemented = "Not Implemented";
    public static final String Bad_Gateway = "Bad Gateway";
    public static final String Service_Unavailable = "Service Unavailable";
    public static final String Gateway_Timeout = "Gateway Timeout";
    public static final String HTTP_Version_Not_Supported = "HTTP Version Not Supported";
    public static final String Insufficient_Storage = "Insufficient Storage";
    public static final String Unknown = "Unknown";
    public static final int ORDINAL_100_Continue = 100;
    public static final int ORDINAL_101_Switching_Protocols = 101;
    public static final int ORDINAL_102_Processing = 102;
    public static final int ORDINAL_200_OK = 200;
    public static final int ORDINAL_201_Created = 201;
    public static final int ORDINAL_202_Accepted = 202;
    public static final int ORDINAL_203_Non_Authoritative_Information = 203;
    public static final int ORDINAL_204_No_Content = 204;
    public static final int ORDINAL_205_Reset_Content = 205;
    public static final int ORDINAL_206_Partial_Content = 206;
    public static final int ORDINAL_207_Multi_Status = 207;
    public static final int ORDINAL_300_Multiple_Choices = 300;
    public static final int ORDINAL_301_Moved_Permanently = 301;
    public static final int ORDINAL_302_Moved_Temporarily = 302;
    public static final int ORDINAL_302_Found = 302;
    public static final int ORDINAL_303_See_Other = 303;
    public static final int ORDINAL_304_Not_Modified = 304;
    public static final int ORDINAL_305_Use_Proxy = 305;
    public static final int ORDINAL_400_Bad_Request = 400;
    public static final int ORDINAL_401_Unauthorized = 401;
    public static final int ORDINAL_402_Payment_Required = 402;
    public static final int ORDINAL_403_Forbidden = 403;
    public static final int ORDINAL_404_Not_Found = 404;
    public static final int ORDINAL_405_Method_Not_Allowed = 405;
    public static final int ORDINAL_406_Not_Acceptable = 406;
    public static final int ORDINAL_407_Proxy_Authentication_Required = 407;
    public static final int ORDINAL_408_Request_Timeout = 408;
    public static final int ORDINAL_409_Conflict = 409;
    public static final int ORDINAL_410_Gone = 410;
    public static final int ORDINAL_411_Length_Required = 411;
    public static final int ORDINAL_412_Precondition_Failed = 412;
    public static final int ORDINAL_413_Request_Entity_Too_Large = 413;
    public static final int ORDINAL_414_Request_URI_Too_Large = 414;
    public static final int ORDINAL_415_Unsupported_Media_Type = 415;
    public static final int ORDINAL_416_Requested_Range_Not_Satisfiable = 416;
    public static final int ORDINAL_417_Expectation_Failed = 417;
    public static final int ORDINAL_422_Unprocessable_Entity = 422;
    public static final int ORDINAL_423_Locked = 423;
    public static final int ORDINAL_424_Failed_Dependency = 424;
    public static final int ORDINAL_500_Internal_Server_Error = 500;
    public static final int ORDINAL_501_Not_Implemented = 501;
    public static final int ORDINAL_502_Bad_Gateway = 502;
    public static final int ORDINAL_503_Service_Unavailable = 503;
    public static final int ORDINAL_504_Gateway_Timeout = 504;
    public static final int ORDINAL_505_HTTP_Version_Not_Supported = 505;
    public static final int ORDINAL_507_Insufficient_Storage = 507;
    public static final int ORDINAL_999_Unknown = 999;
    public static final BufferCache CACHE;
    public static final Buffer Continue_BUFFER;
    public static final Buffer Switching_Protocols_BUFFER;
    public static final Buffer Processing_BUFFER;
    public static final Buffer OK_BUFFER;
    public static final Buffer Created_BUFFER;
    public static final Buffer Accepted_BUFFER;
    public static final Buffer Non_Authoritative_Information_BUFFER;
    public static final Buffer No_Content_BUFFER;
    public static final Buffer Reset_Content_BUFFER;
    public static final Buffer Partial_Content_BUFFER;
    public static final Buffer Multi_Status_BUFFER;
    public static final Buffer Multiple_Choices_BUFFER;
    public static final Buffer Moved_Permanently_BUFFER;
    public static final Buffer Moved_Temporarily_BUFFER;
    public static final Buffer Found_BUFFER;
    public static final Buffer See_Other_BUFFER;
    public static final Buffer Not_Modified_BUFFER;
    public static final Buffer Use_Proxy_BUFFER;
    public static final Buffer Bad_Request_BUFFER;
    public static final Buffer Unauthorized_BUFFER;
    public static final Buffer Payment_Required_BUFFER;
    public static final Buffer Forbidden_BUFFER;
    public static final Buffer Not_Found_BUFFER;
    public static final Buffer Method_Not_Allowed_BUFFER;
    public static final Buffer Not_Acceptable_BUFFER;
    public static final Buffer Proxy_Authentication_Required_BUFFER;
    public static final Buffer Request_Timeout_BUFFER;
    public static final Buffer Conflict_BUFFER;
    public static final Buffer Gone_BUFFER;
    public static final Buffer Length_Required_BUFFER;
    public static final Buffer Precondition_Failed_BUFFER;
    public static final Buffer Request_Entity_Too_Large_BUFFER;
    public static final Buffer Request_URI_Too_Large_BUFFER;
    public static final Buffer Unsupported_Media_Type_BUFFER;
    public static final Buffer Requested_Range_Not_Satisfiable_BUFFER;
    public static final Buffer Expectation_Failed_BUFFER;
    public static final Buffer Unprocessable_Entity_BUFFER;
    public static final Buffer Locked_BUFFER;
    public static final Buffer Failed_Dependency_BUFFER;
    public static final Buffer Internal_Server_Error_BUFFER;
    public static final Buffer Not_Implemented_BUFFER;
    public static final Buffer Bad_Gateway_BUFFER;
    public static final Buffer Service_Unavailable_BUFFER;
    public static final Buffer Gateway_Timeout_BUFFER;
    public static final Buffer HTTP_Version_Not_Supported_BUFFER;
    public static final Buffer Insufficient_Storage_BUFFER;
    public static final Buffer Unknown_BUFFER;
    private static Buffer[] __responseLine;
    
    public static Buffer getResponseLine(final int status) {
        if (status >= HttpStatus.__responseLine.length) {
            return null;
        }
        return HttpStatus.__responseLine[status];
    }
    
    static {
        CACHE = new BufferCache();
        Continue_BUFFER = HttpStatus.CACHE.add("Continue", 100);
        Switching_Protocols_BUFFER = HttpStatus.CACHE.add("Switching Protocols", 101);
        Processing_BUFFER = HttpStatus.CACHE.add("Processing", 102);
        OK_BUFFER = HttpStatus.CACHE.add("OK", 200);
        Created_BUFFER = HttpStatus.CACHE.add("Created", 201);
        Accepted_BUFFER = HttpStatus.CACHE.add("Accepted", 202);
        Non_Authoritative_Information_BUFFER = HttpStatus.CACHE.add("Non Authoritative Information", 203);
        No_Content_BUFFER = HttpStatus.CACHE.add("No Content", 204);
        Reset_Content_BUFFER = HttpStatus.CACHE.add("Reset Content", 205);
        Partial_Content_BUFFER = HttpStatus.CACHE.add("Partial Content", 206);
        Multi_Status_BUFFER = HttpStatus.CACHE.add("Multi Status", 207);
        Multiple_Choices_BUFFER = HttpStatus.CACHE.add("Multiple Choices", 300);
        Moved_Permanently_BUFFER = HttpStatus.CACHE.add("Moved Permanently", 301);
        Moved_Temporarily_BUFFER = HttpStatus.CACHE.add("Moved Temporarily", 302);
        Found_BUFFER = HttpStatus.CACHE.add("Found", 302);
        See_Other_BUFFER = HttpStatus.CACHE.add("See Other", 303);
        Not_Modified_BUFFER = HttpStatus.CACHE.add("Not Modified", 304);
        Use_Proxy_BUFFER = HttpStatus.CACHE.add("Use Proxy", 305);
        Bad_Request_BUFFER = HttpStatus.CACHE.add("Bad Request", 400);
        Unauthorized_BUFFER = HttpStatus.CACHE.add("Unauthorized", 401);
        Payment_Required_BUFFER = HttpStatus.CACHE.add("Payment Required", 402);
        Forbidden_BUFFER = HttpStatus.CACHE.add("Forbidden", 403);
        Not_Found_BUFFER = HttpStatus.CACHE.add("Not Found", 404);
        Method_Not_Allowed_BUFFER = HttpStatus.CACHE.add("Method Not Allowed", 405);
        Not_Acceptable_BUFFER = HttpStatus.CACHE.add("Not Acceptable", 406);
        Proxy_Authentication_Required_BUFFER = HttpStatus.CACHE.add("Proxy Authentication Required", 407);
        Request_Timeout_BUFFER = HttpStatus.CACHE.add("Request Timeout", 408);
        Conflict_BUFFER = HttpStatus.CACHE.add("Conflict", 409);
        Gone_BUFFER = HttpStatus.CACHE.add("Gone", 410);
        Length_Required_BUFFER = HttpStatus.CACHE.add("Length Required", 411);
        Precondition_Failed_BUFFER = HttpStatus.CACHE.add("Precondition Failed", 412);
        Request_Entity_Too_Large_BUFFER = HttpStatus.CACHE.add("Request Entity Too Large", 413);
        Request_URI_Too_Large_BUFFER = HttpStatus.CACHE.add("Request URI Too Large", 414);
        Unsupported_Media_Type_BUFFER = HttpStatus.CACHE.add("Unsupported Media Type", 415);
        Requested_Range_Not_Satisfiable_BUFFER = HttpStatus.CACHE.add("Requested Range Not Satisfiable", 416);
        Expectation_Failed_BUFFER = HttpStatus.CACHE.add("Expectation Failed", 417);
        Unprocessable_Entity_BUFFER = HttpStatus.CACHE.add("Unprocessable Entity", 422);
        Locked_BUFFER = HttpStatus.CACHE.add("Locked", 423);
        Failed_Dependency_BUFFER = HttpStatus.CACHE.add("Failed Dependency", 424);
        Internal_Server_Error_BUFFER = HttpStatus.CACHE.add("Internal Server Error", 500);
        Not_Implemented_BUFFER = HttpStatus.CACHE.add("Not Implemented", 501);
        Bad_Gateway_BUFFER = HttpStatus.CACHE.add("Bad Gateway", 502);
        Service_Unavailable_BUFFER = HttpStatus.CACHE.add("Service Unavailable", 503);
        Gateway_Timeout_BUFFER = HttpStatus.CACHE.add("Gateway Timeout", 504);
        HTTP_Version_Not_Supported_BUFFER = HttpStatus.CACHE.add("HTTP Version Not Supported", 505);
        Insufficient_Storage_BUFFER = HttpStatus.CACHE.add("Insufficient Storage", 507);
        Unknown_BUFFER = HttpStatus.CACHE.add("Unknown", 999);
        HttpStatus.__responseLine = new Buffer[600];
        final int versionLength = HttpVersions.HTTP_1_1_BUFFER.length();
        for (int i = 0; i < HttpStatus.__responseLine.length; ++i) {
            final Buffer reason = HttpStatus.CACHE.get(i);
            if (reason != null) {
                final byte[] bytes = new byte[versionLength + 5 + reason.length() + 2];
                HttpVersions.HTTP_1_1_BUFFER.peek(0, bytes, 0, versionLength);
                bytes[versionLength + 0] = 32;
                bytes[versionLength + 1] = (byte)(48 + i / 100);
                bytes[versionLength + 2] = (byte)(48 + i % 100 / 10);
                bytes[versionLength + 3] = (byte)(48 + i % 10);
                bytes[versionLength + 4] = 32;
                reason.peek(0, bytes, versionLength + 5, reason.length());
                bytes[versionLength + 5 + reason.length()] = 13;
                bytes[versionLength + 6 + reason.length()] = 10;
                HttpStatus.__responseLine[i] = new ByteArrayBuffer(bytes, 0, bytes.length, 0);
            }
        }
    }
}
